pluginManagement {
    repositories {
        gradlePluginPortal()
        maven { url = 'https://maven.neoforged.net/releases' }
        mavenCentral()
    }
}

plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '1.0.0'
}

rootProject.name = 'confluxmap-neoforge'
include ':common'

file('versions').eachDir { final File dir ->
    if (new File(dir, 'build.gradle').exists()) {
        final String version = ":$dir.name"
        include version
        project(version).projectDir = dir
    }
}
